import type { LexemaSemilla } from '../types';

// Chengyu (成语) adicionales con ejemplo de uso real. Ids con prefijo c_.
export const CHENGYU_EXTRA: readonly LexemaSemilla[] = [
  {
    id: 'c_shibangongbei',
    hanzi: '事半功倍',
    pinyin: 'shì bàn gōng bèi',
    es: 'lograr el doble con la mitad del esfuerzo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '用对方法学习，往往能事半功倍。',
      pinyin: 'Yòng duì fāngfǎ xuéxí, wǎngwǎng néng shì bàn gōng bèi.',
      es: 'Estudiar con el método adecuado suele rendir el doble con la mitad del esfuerzo.',
    },
  },
  {
    id: 'c_quanliyifu',
    hanzi: '全力以赴',
    pinyin: 'quán lì yǐ fù',
    es: 'darlo todo, esforzarse al máximo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '为了这次比赛，他全力以赴。',
      pinyin: 'Wèile zhè cì bǐsài, tā quán lì yǐ fù.',
      es: 'Para esta competición, lo dio absolutamente todo.',
    },
  },
  {
    id: 'c_yibudengtian',
    hanzi: '一步登天',
    pinyin: 'yí bù dēng tiān',
    es: 'subir al cielo de un paso; triunfar de golpe',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '成功需要积累，没有人能一步登天。',
      pinyin: 'Chénggōng xūyào jīlěi, méiyǒu rén néng yí bù dēng tiān.',
      es: 'El éxito requiere acumulación; nadie triunfa de golpe.',
    },
  },
  {
    id: 'c_buchixiawen',
    hanzi: '不耻下问',
    pinyin: 'bù chǐ xià wèn',
    es: 'no avergonzarse de preguntar a un inferior',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '真正的学者往往不耻下问。',
      pinyin: 'Zhēnzhèng de xuézhě wǎngwǎng bù chǐ xià wèn.',
      es: 'Los verdaderos eruditos no se avergüenzan de preguntar a quien sabe menos.',
    },
  },
  {
    id: 'c_chizhiyiheng',
    hanzi: '持之以恒',
    pinyin: 'chí zhī yǐ héng',
    es: 'perseverar con constancia',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '学外语贵在持之以恒。',
      pinyin: 'Xué wàiyǔ guì zài chí zhī yǐ héng.',
      es: 'En el aprendizaje de idiomas, lo valioso es la constancia.',
    },
  },
  {
    id: 'c_yiriqianli',
    hanzi: '一日千里',
    pinyin: 'yí rì qiān lǐ',
    es: 'mil li en un día; progresar a pasos agigantados',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '近年来，科技发展一日千里。',
      pinyin: 'Jìnnián lái, kējì fāzhǎn yí rì qiān lǐ.',
      es: 'En los últimos años, la tecnología avanza a pasos agigantados.',
    },
  },
  {
    id: 'c_haobuyouyu',
    hanzi: '毫不犹豫',
    pinyin: 'háo bù yóuyù',
    es: 'sin la menor vacilación',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '他毫不犹豫地答应了。',
      pinyin: 'Tā háo bù yóuyù de dāyìng le.',
      es: 'Aceptó sin la menor vacilación.',
    },
  },
  {
    id: 'c_yiwusuozhi',
    hanzi: '一无所知',
    pinyin: 'yì wú suǒ zhī',
    es: 'no saber absolutamente nada',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '对于这件事，我一无所知。',
      pinyin: 'Duìyú zhè jiàn shì, wǒ yì wú suǒ zhī.',
      es: 'Sobre este asunto no sé absolutamente nada.',
    },
  },
  {
    id: 'c_xinxinxiangrong',
    hanzi: '欣欣向荣',
    pinyin: 'xīn xīn xiàng róng',
    es: 'florecer y prosperar',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '春天来了，万物欣欣向荣。',
      pinyin: 'Chūntiān lái le, wànwù xīn xīn xiàng róng.',
      es: 'Llegó la primavera y todo florece y prospera.',
    },
  },
  {
    id: 'c_feiqinwangshi',
    hanzi: '废寝忘食',
    pinyin: 'fèi qǐn wàng shí',
    es: 'olvidar el sueño y la comida; volcarse por completo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '为了完成项目，他废寝忘食。',
      pinyin: 'Wèile wánchéng xiàngmù, tā fèi qǐn wàng shí.',
      es: 'Para terminar el proyecto, se olvidó de comer y dormir.',
    },
  },
  {
    id: 'c_shuiluoshichu',
    hanzi: '水落石出',
    pinyin: 'shuǐ luò shí chū',
    es: 'cuando baja el agua aparecen las piedras; salir la verdad a la luz',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '随着调查深入，真相终于水落石出。',
      pinyin: 'Suízhe diàochá shēnrù, zhēnxiàng zhōngyú shuǐ luò shí chū.',
      es: 'A medida que avanzó la investigación, la verdad salió a la luz.',
    },
  },
];
