import type { LexemaSemilla } from '../types';

// 18 chengyu (成语) con ejemplo de uso real.
export const CHENGYU: readonly LexemaSemilla[] = [
  {
    id: 'c_huashetianzu',
    hanzi: '画蛇添足',
    pinyin: 'huà shé tiān zú',
    es: 'dibujar patas a una serpiente; arruinar algo por exceso',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '你已经解释清楚了，再补充就是画蛇添足。',
      es: 'Ya lo explicaste bien; añadir más es pasarse.',
    },
  },
  {
    id: 'c_ruxiangsuisu',
    hanzi: '入乡随俗',
    pinyin: 'rù xiāng suí sú',
    es: 'donde fueres, haz lo que vieres',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '到了中国就要入乡随俗，学着用筷子吧。',
      es: 'En China, adáptate: aprende a usar los palillos.',
    },
  },
  {
    id: 'c_yijuliangde',
    hanzi: '一举两得',
    pinyin: 'yī jǔ liǎng dé',
    es: 'matar dos pájaros de un tiro',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '骑车上班既省钱又锻炼身体，真是一举两得。',
      es: 'Ir en bici al trabajo ahorra y ejercita: dos en uno.',
    },
  },
  {
    id: 'c_bantuerfei',
    hanzi: '半途而废',
    pinyin: 'bàn tú ér fèi',
    es: 'abandonar a mitad de camino',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '学语言最忌半途而废，要坚持下去。',
      es: 'En idiomas, lo peor es dejarlo a medias: hay que persistir.',
    },
  },
  {
    id: 'c_rumusanfen',
    hanzi: '入木三分',
    pinyin: 'rù mù sān fēn',
    es: 'penetrante, certero (análisis muy agudo)',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '他对社会问题的分析入木三分。',
      es: 'Su análisis de los problemas sociales es muy agudo.',
    },
  },
  {
    id: 'c_mingfuqishi',
    hanzi: '名副其实',
    pinyin: 'míng fù qí shí',
    es: 'hacer honor a su nombre; merecido',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '她是名副其实的专家，大家都信服。',
      es: 'Es una experta de verdad; todos la respetan.',
    },
  },
  {
    id: 'c_bukesiyi',
    hanzi: '不可思议',
    pinyin: 'bù kě sī yì',
    es: 'inconcebible, increíble',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '短短几年变化这么大，简直不可思议。',
      es: 'Tanto cambio en pocos años es increíble.',
    },
  },
  {
    id: 'c_shouzhudaitu',
    hanzi: '守株待兔',
    pinyin: 'shǒu zhū dài tù',
    es: 'confiar en la suerte sin esfuerzo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '不努力只想中奖，无异于守株待兔。',
      es: 'Esperar el premio sin esforzarse es confiar en la suerte.',
    },
  },
  {
    id: 'c_duiniutanqin',
    hanzi: '对牛弹琴',
    pinyin: 'duì niú tán qín',
    es: 'hablar a quien no entiende',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '跟他讲艺术简直是对牛弹琴。',
      es: 'Hablarle de arte es predicar en el desierto.',
    },
  },
  {
    id: 'c_hualongdianjing',
    hanzi: '画龙点睛',
    pinyin: 'huà lóng diǎn jīng',
    es: 'el toque maestro que da vida al conjunto',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '这句结尾真是画龙点睛，全文都活了。',
      es: 'Ese final es el toque maestro: da vida a todo el texto.',
    },
  },
  {
    id: 'c_zixiangmaodun',
    hanzi: '自相矛盾',
    pinyin: 'zì xiāng máo dùn',
    es: 'contradecirse a sí mismo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '他的说法前后自相矛盾。',
      es: 'Su versión se contradice de principio a fin.',
    },
  },
  {
    id: 'c_qirenyoutian',
    hanzi: '杞人忧天',
    pinyin: 'qǐ rén yōu tiān',
    es: 'preocuparse sin motivo',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '别杞人忧天了，事情没你想的那么糟。',
      es: 'No te angusties sin motivo; no es tan grave.',
    },
  },
  {
    id: 'c_saiwengshima',
    hanzi: '塞翁失马',
    pinyin: 'sài wēng shī mǎ',
    es: 'no hay mal que por bien no venga',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '失业后他创了业，真是塞翁失马。',
      es: 'Tras perder el empleo, emprendió: no hay mal que por bien no venga.',
    },
  },
  {
    id: 'c_jingdizhiwa',
    hanzi: '井底之蛙',
    pinyin: 'jǐng dǐ zhī wā',
    es: 'la rana del pozo; visión estrecha',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '不出去看看世界，就会变成井底之蛙。',
      es: 'Si no sales a ver el mundo, tu visión se estrecha.',
    },
  },
  {
    id: 'c_jinshangtianhua',
    hanzi: '锦上添花',
    pinyin: 'jǐn shàng tiān huā',
    es: 'mejorar lo que ya es bueno',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: { hanzi: '有了你的帮助，真是锦上添花。', es: 'Con tu ayuda, todo mejora aún más.' },
  },
  {
    id: 'c_xuezhongsongtan',
    hanzi: '雪中送炭',
    pinyin: 'xuě zhōng sòng tàn',
    es: 'ayudar en el momento crítico',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '我最困难时是他雪中送炭。',
      es: 'En mi peor momento, él me ayudó justo cuando lo necesitaba.',
    },
  },
  {
    id: 'c_luoyibujue',
    hanzi: '络绎不绝',
    pinyin: 'luò yì bù jué',
    es: 'flujo continuo, sin interrupción',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '展览期间，参观的人络绎不绝。',
      es: 'Durante la exposición, el público no paraba de llegar.',
    },
  },
  {
    id: 'c_yisibugou',
    hanzi: '一丝不苟',
    pinyin: 'yī sī bù gǒu',
    es: 'meticuloso, sin descuidar el detalle',
    hsk: 7,
    esChengyu: true,
    dificultad: 7,
    tags: ['chengyu'],
    ejemplo: {
      hanzi: '他工作一丝不苟，从不出错。',
      es: 'Trabaja con suma meticulosidad; nunca falla.',
    },
  },
];
