import type { LexemaSemilla } from '../types';

// Contenido HSK 5-6 adicional, temático (viajes, tecnología, salud, trabajo, emociones).
// Ids únicos con prefijo w_ para encajar con el resto del vocabulario semilla.
export const HSK_EXTRA: readonly LexemaSemilla[] = [
  // --- Viajes ---
  {
    id: 'w_hangban',
    hanzi: '航班',
    pinyin: 'hángbān',
    es: 'vuelo (de avión)',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['viajes'],
    ejemplo: {
      hanzi: '我们的航班因为大雪延误了。',
      pinyin: 'Wǒmen de hángbān yīnwèi dàxuě yánwù le.',
      es: 'Nuestro vuelo se retrasó por la nevada.',
    },
  },
  {
    id: 'w_qianzheng',
    hanzi: '签证',
    pinyin: 'qiānzhèng',
    es: 'visado',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['viajes'],
    ejemplo: {
      hanzi: '去那个国家需要提前办签证。',
      pinyin: 'Qù nàge guójiā xūyào tíqián bàn qiānzhèng.',
      es: 'Para ir a ese país hay que tramitar el visado con antelación.',
    },
  },
  {
    id: 'w_xinglixiang',
    hanzi: '行李箱',
    pinyin: 'xínglixiāng',
    es: 'maleta',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['viajes'],
    ejemplo: {
      hanzi: '我的行李箱太重，超过了重量限制。',
      pinyin: 'Wǒ de xínglixiāng tài zhòng, chāoguò le zhòngliàng xiànzhì.',
      es: 'Mi maleta pesa demasiado, supera el límite de peso.',
    },
  },
  {
    id: 'w_mingsheng',
    hanzi: '名胜',
    pinyin: 'míngshèng',
    es: 'lugar pintoresco, atracción turística',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['viajes'],
    ejemplo: {
      hanzi: '这座城市有很多著名的名胜古迹。',
      pinyin: 'Zhè zuò chéngshì yǒu hěnduō zhùmíng de míngshèng gǔjì.',
      es: 'Esta ciudad tiene muchos lugares pintorescos y monumentos famosos.',
    },
  },
  // --- Tecnología ---
  {
    id: 'w_xiazai',
    hanzi: '下载',
    pinyin: 'xiàzài',
    es: 'descargar',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['tecnologia'],
    ejemplo: {
      hanzi: '请先下载这个应用程序。',
      pinyin: 'Qǐng xiān xiàzài zhège yìngyòng chéngxù.',
      es: 'Por favor, descarga primero esta aplicación.',
    },
  },
  {
    id: 'w_pingmu',
    hanzi: '屏幕',
    pinyin: 'píngmù',
    es: 'pantalla',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['tecnologia'],
    ejemplo: {
      hanzi: '手机屏幕摔碎了。',
      pinyin: 'Shǒujī píngmù shuāisuì le.',
      es: 'La pantalla del móvil se rompió al caerse.',
    },
  },
  {
    id: 'w_shuju',
    hanzi: '数据',
    pinyin: 'shùjù',
    es: 'datos',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['tecnologia', 'trabajo'],
    ejemplo: {
      hanzi: '这份报告基于大量的数据分析。',
      pinyin: 'Zhè fèn bàogào jīyú dàliàng de shùjù fēnxī.',
      es: 'Este informe se basa en un amplio análisis de datos.',
    },
  },
  {
    id: 'w_rengong_zhineng',
    hanzi: '人工智能',
    pinyin: 'réngōng zhìnéng',
    es: 'inteligencia artificial',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['tecnologia'],
    ejemplo: {
      hanzi: '人工智能正在改变我们的生活。',
      pinyin: 'Réngōng zhìnéng zhèngzài gǎibiàn wǒmen de shēnghuó.',
      es: 'La inteligencia artificial está transformando nuestra vida.',
    },
  },
  {
    id: 'w_wangluo',
    hanzi: '网络',
    pinyin: 'wǎngluò',
    es: 'red, internet',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['tecnologia'],
    ejemplo: {
      hanzi: '这里的网络信号不太好。',
      pinyin: 'Zhèlǐ de wǎngluò xìnhào bú tài hǎo.',
      es: 'La señal de internet aquí no es muy buena.',
    },
  },
  // --- Salud ---
  {
    id: 'w_zhengzhuang',
    hanzi: '症状',
    pinyin: 'zhèngzhuàng',
    es: 'síntoma',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['salud'],
    ejemplo: {
      hanzi: '请把你的症状告诉医生。',
      pinyin: 'Qǐng bǎ nǐ de zhèngzhuàng gàosù yīshēng.',
      es: 'Por favor, cuéntale tus síntomas al médico.',
    },
  },
  {
    id: 'w_mianyi',
    hanzi: '免疫',
    pinyin: 'miǎnyì',
    es: 'inmunidad, inmune',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['salud'],
    ejemplo: {
      hanzi: '充足的睡眠能增强免疫力。',
      pinyin: 'Chōngzú de shuìmián néng zēngqiáng miǎnyìlì.',
      es: 'Dormir lo suficiente refuerza la inmunidad.',
    },
  },
  {
    id: 'w_kangfu',
    hanzi: '康复',
    pinyin: 'kāngfù',
    es: 'recuperarse, rehabilitación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['salud'],
    ejemplo: {
      hanzi: '经过几周的治疗，他终于康复了。',
      pinyin: 'Jīngguò jǐ zhōu de zhìliáo, tā zhōngyú kāngfù le.',
      es: 'Tras varias semanas de tratamiento, por fin se recuperó.',
    },
  },
  {
    id: 'w_yingyang',
    hanzi: '营养',
    pinyin: 'yíngyǎng',
    es: 'nutrición',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['salud'],
    ejemplo: {
      hanzi: '蔬菜和水果富含营养。',
      pinyin: 'Shūcài hé shuǐguǒ fùhán yíngyǎng.',
      es: 'Las verduras y la fruta son ricas en nutrientes.',
    },
  },
  // --- Trabajo ---
  {
    id: 'w_jianli',
    hanzi: '简历',
    pinyin: 'jiǎnlì',
    es: 'currículum',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['trabajo'],
    ejemplo: {
      hanzi: '请把你的简历发到这个邮箱。',
      pinyin: 'Qǐng bǎ nǐ de jiǎnlì fā dào zhège yóuxiāng.',
      es: 'Por favor, envía tu currículum a este correo.',
    },
  },
  {
    id: 'w_mianshi',
    hanzi: '面试',
    pinyin: 'miànshì',
    es: 'entrevista (de trabajo)',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['trabajo'],
    ejemplo: {
      hanzi: '她明天要去一家公司面试。',
      pinyin: 'Tā míngtiān yào qù yì jiā gōngsī miànshì.',
      es: 'Mañana tiene una entrevista en una empresa.',
    },
  },
  {
    id: 'w_xiezuo',
    hanzi: '协作',
    pinyin: 'xiézuò',
    es: 'colaborar, cooperación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['trabajo'],
    ejemplo: {
      hanzi: '团队协作是成功的关键。',
      pinyin: 'Tuánduì xiézuò shì chénggōng de guānjiàn.',
      es: 'La colaboración en equipo es la clave del éxito.',
    },
  },
  {
    id: 'w_qianyue',
    hanzi: '签约',
    pinyin: 'qiānyuē',
    es: 'firmar un contrato',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['trabajo'],
    ejemplo: {
      hanzi: '双方今天正式签约。',
      pinyin: 'Shuāngfāng jīntiān zhèngshì qiānyuē.',
      es: 'Ambas partes firman el contrato oficialmente hoy.',
    },
  },
  {
    id: 'w_shengzhi',
    hanzi: '升职',
    pinyin: 'shēngzhí',
    es: 'ascender (en el trabajo)',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['trabajo'],
    ejemplo: {
      hanzi: '努力工作了三年，他终于升职了。',
      pinyin: 'Nǔlì gōngzuò le sān nián, tā zhōngyú shēngzhí le.',
      es: 'Tras tres años de duro trabajo, por fin ascendió.',
    },
  },
  // --- Emociones ---
  {
    id: 'w_xingfu',
    hanzi: '幸福',
    pinyin: 'xìngfú',
    es: 'felicidad, dichoso',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '一家人在一起就是幸福。',
      pinyin: 'Yì jiā rén zài yìqǐ jiùshì xìngfú.',
      es: 'Estar toda la familia junta ya es la felicidad.',
    },
  },
  {
    id: 'w_jusang',
    hanzi: '沮丧',
    pinyin: 'jǔsàng',
    es: 'desanimado, abatido',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '考试失败让他很沮丧。',
      pinyin: 'Kǎoshì shībài ràng tā hěn jǔsàng.',
      es: 'Suspender el examen lo dejó muy abatido.',
    },
  },
  {
    id: 'w_xingfen',
    hanzi: '兴奋',
    pinyin: 'xīngfèn',
    es: 'emocionado, entusiasmado',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '听到这个消息，孩子们都很兴奋。',
      pinyin: 'Tīngdào zhège xiāoxi, háizimen dōu hěn xīngfèn.',
      es: 'Al oír la noticia, los niños se pusieron muy emocionados.',
    },
  },
  {
    id: 'w_kongju',
    hanzi: '恐惧',
    pinyin: 'kǒngjù',
    es: 'miedo, temor',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '面对未知，人们常常感到恐惧。',
      pinyin: 'Miànduì wèizhī, rénmen chángcháng gǎndào kǒngjù.',
      es: 'Ante lo desconocido, la gente suele sentir temor.',
    },
  },
  {
    id: 'w_xinwei',
    hanzi: '欣慰',
    pinyin: 'xīnwèi',
    es: 'gratamente aliviado, reconfortado',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '看到孩子健康成长，父母感到很欣慰。',
      pinyin: 'Kàndào háizi jiànkāng chéngzhǎng, fùmǔ gǎndào hěn xīnwèi.',
      es: 'Ver crecer sanos a sus hijos reconforta a los padres.',
    },
  },
  {
    id: 'w_zibei',
    hanzi: '自卑',
    pinyin: 'zìbēi',
    es: 'complejo de inferioridad, sentirse inferior',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emociones'],
    ejemplo: {
      hanzi: '不要因为一次失败就感到自卑。',
      pinyin: 'Búyào yīnwèi yí cì shībài jiù gǎndào zìbēi.',
      es: 'No te sientas inferior por un solo fracaso.',
    },
  },
];
