import type { LexemaSemilla } from '../types';

// 26 palabras HSK 5-6 tematizadas (economía / sociedad / "neijuan"), con ejemplo de uso.
export const HSK: readonly LexemaSemilla[] = [
  {
    id: 'w_jingji',
    hanzi: '经济',
    pinyin: 'jīngjì',
    es: 'economía',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
    ejemplo: {
      hanzi: '中国的经济发展得很快。',
      es: 'La economía de China se desarrolla muy rápido.',
    },
  },
  {
    id: 'w_qushi',
    hanzi: '趋势',
    pinyin: 'qūshì',
    es: 'tendencia',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
    ejemplo: { hanzi: '这是不可避免的趋势。', es: 'Es una tendencia inevitable.' },
  },
  {
    id: 'w_xiaolv',
    hanzi: '效率',
    pinyin: 'xiàolǜ',
    es: 'eficiencia',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['trabajo', 'neijuan'],
    ejemplo: {
      hanzi: '用这个工具能提高效率。',
      es: 'Con esta herramienta se mejora la eficiencia.',
    },
  },
  {
    id: 'w_jiaolv',
    hanzi: '焦虑',
    pinyin: 'jiāolǜ',
    es: 'ansiedad',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad', 'neijuan'],
    ejemplo: { hanzi: '考试前他感到很焦虑。', es: 'Antes del examen se sentía muy ansioso.' },
  },
  {
    id: 'w_peiyang',
    hanzi: '培养',
    pinyin: 'péiyǎng',
    es: 'cultivar, formar',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['educacion'],
    ejemplo: {
      hanzi: '父母应该培养孩子的兴趣。',
      es: 'Los padres deben cultivar los intereses de sus hijos.',
    },
  },
  {
    id: 'w_pingheng',
    hanzi: '平衡',
    pinyin: 'pínghéng',
    es: 'equilibrio',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
    ejemplo: {
      hanzi: '工作和生活要保持平衡。',
      es: 'Hay que mantener el equilibrio entre el trabajo y la vida.',
    },
  },
  {
    id: 'w_ziyuan',
    hanzi: '资源',
    pinyin: 'zīyuán',
    es: 'recurso',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
    ejemplo: { hanzi: '我们要节约资源。', es: 'Debemos ahorrar recursos.' },
  },
  {
    id: 'w_xianxiang',
    hanzi: '现象',
    pinyin: 'xiànxiàng',
    es: 'fenómeno',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
    ejemplo: { hanzi: '这是一种普遍的社会现象。', es: 'Es un fenómeno social muy extendido.' },
  },
  {
    id: 'w_guannian',
    hanzi: '观念',
    pinyin: 'guānniàn',
    es: 'concepto, mentalidad',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
    ejemplo: { hanzi: '他的观念比较传统。', es: 'Su mentalidad es bastante tradicional.' },
  },
  {
    id: 'w_zeren',
    hanzi: '责任',
    pinyin: 'zérèn',
    es: 'responsabilidad',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
    ejemplo: {
      hanzi: '保护环境是每个人的责任。',
      es: 'Proteger el medio ambiente es responsabilidad de todos.',
    },
  },
  {
    id: 'w_quefa',
    hanzi: '缺乏',
    pinyin: 'quēfá',
    es: 'carecer de, falta',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['general'],
    ejemplo: { hanzi: '他缺乏工作经验。', es: 'Le falta experiencia laboral.' },
  },
  {
    id: 'w_chengdan',
    hanzi: '承担',
    pinyin: 'chéngdān',
    es: 'asumir (responsabilidad)',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['trabajo'],
    ejemplo: { hanzi: '这个后果由你来承担。', es: 'Las consecuencias las asumes tú.' },
  },
  {
    id: 'w_maodun',
    hanzi: '矛盾',
    pinyin: 'máodùn',
    es: 'contradicción, conflicto',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
    ejemplo: { hanzi: '他们之间产生了矛盾。', es: 'Surgió un conflicto entre ellos.' },
  },
  {
    id: 'w_tuoxie',
    hanzi: '妥协',
    pinyin: 'tuǒxié',
    es: 'ceder, transigir',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
    ejemplo: { hanzi: '双方最后做出了妥协。', es: 'Ambas partes acabaron cediendo.' },
  },
  {
    id: 'w_jinshen',
    hanzi: '谨慎',
    pinyin: 'jǐnshèn',
    es: 'prudente, cauteloso',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['caracter'],
    ejemplo: {
      hanzi: '做重要决定时要谨慎。',
      es: 'Hay que ser prudente al tomar decisiones importantes.',
    },
  },
  {
    id: 'w_xianzhu',
    hanzi: '显著',
    pinyin: 'xiǎnzhù',
    es: 'notable, significativo',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
    ejemplo: { hanzi: '治疗的效果非常显著。', es: 'El efecto del tratamiento es muy notable.' },
  },
  {
    id: 'w_juxian',
    hanzi: '局限',
    pinyin: 'júxiàn',
    es: 'limitación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
    ejemplo: { hanzi: '这种方法有很大的局限。', es: 'Este método tiene grandes limitaciones.' },
  },
  {
    id: 'w_qingxiang',
    hanzi: '倾向',
    pinyin: 'qīngxiàng',
    es: 'inclinación, tendencia',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
    ejemplo: { hanzi: '我更倾向于第一个方案。', es: 'Me inclino más por la primera opción.' },
  },
  {
    id: 'w_hengliang',
    hanzi: '衡量',
    pinyin: 'héngliáng',
    es: 'sopesar, evaluar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
    ejemplo: { hanzi: '我们需要衡量利弊。', es: 'Necesitamos sopesar los pros y los contras.' },
  },
  {
    id: 'w_boxue',
    hanzi: '剥削',
    pinyin: 'bōxuē',
    es: 'explotación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['economia', 'neijuan'],
    ejemplo: {
      hanzi: '工人受到了严重的剥削。',
      es: 'Los trabajadores sufrieron una grave explotación.',
    },
  },
  {
    id: 'w_kewang',
    hanzi: '渴望',
    pinyin: 'kěwàng',
    es: 'anhelar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emocion'],
    ejemplo: { hanzi: '年轻人渴望成功。', es: 'Los jóvenes anhelan el éxito.' },
  },
  {
    id: 'w_chenmo',
    hanzi: '沉默',
    pinyin: 'chénmò',
    es: 'silencio, callar',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['emocion'],
    ejemplo: { hanzi: '面对批评，他选择了沉默。', es: 'Ante las críticas, optó por el silencio.' },
  },
  {
    id: 'w_pangda',
    hanzi: '庞大',
    pinyin: 'pángdà',
    es: 'enorme, colosal',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
    ejemplo: { hanzi: '这是一个庞大的工程。', es: 'Es un proyecto colosal.' },
  },
  {
    id: 'w_ningju',
    hanzi: '凝聚',
    pinyin: 'níngjù',
    es: 'aglutinar, cohesionar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
    ejemplo: { hanzi: '这件事凝聚了大家的力量。', es: 'Este asunto aglutinó la fuerza de todos.' },
  },
  {
    id: 'w_yanjun',
    hanzi: '严峻',
    pinyin: 'yánjùn',
    es: 'severo, crítico (situación)',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
    ejemplo: { hanzi: '就业形势非常严峻。', es: 'La situación del empleo es muy crítica.' },
  },
  {
    id: 'w_qianli',
    hanzi: '潜力',
    pinyin: 'qiánlì',
    es: 'potencial',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['general'],
    ejemplo: { hanzi: '这个市场有很大的潜力。', es: 'Este mercado tiene un gran potencial.' },
  },
];
