import type { LexemaSemilla } from '../types';

// 26 palabras HSK 5-6 tematizadas (economía / sociedad / "neijuan").
export const HSK: readonly LexemaSemilla[] = [
  {
    id: 'w_jingji',
    hanzi: '经济',
    pinyin: 'jīngjì',
    es: 'economía',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
  },
  {
    id: 'w_qushi',
    hanzi: '趋势',
    pinyin: 'qūshì',
    es: 'tendencia',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
  },
  {
    id: 'w_xiaolv',
    hanzi: '效率',
    pinyin: 'xiàolǜ',
    es: 'eficiencia',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['trabajo', 'neijuan'],
  },
  {
    id: 'w_jiaolv',
    hanzi: '焦虑',
    pinyin: 'jiāolǜ',
    es: 'ansiedad',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad', 'neijuan'],
  },
  {
    id: 'w_peiyang',
    hanzi: '培养',
    pinyin: 'péiyǎng',
    es: 'cultivar, formar',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['educacion'],
  },
  {
    id: 'w_pingheng',
    hanzi: '平衡',
    pinyin: 'pínghéng',
    es: 'equilibrio',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
  },
  {
    id: 'w_ziyuan',
    hanzi: '资源',
    pinyin: 'zīyuán',
    es: 'recurso',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['economia'],
  },
  {
    id: 'w_xianxiang',
    hanzi: '现象',
    pinyin: 'xiànxiàng',
    es: 'fenómeno',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
  },
  {
    id: 'w_guannian',
    hanzi: '观念',
    pinyin: 'guānniàn',
    es: 'concepto, mentalidad',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
  },
  {
    id: 'w_zeren',
    hanzi: '责任',
    pinyin: 'zérèn',
    es: 'responsabilidad',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
  },
  {
    id: 'w_quefa',
    hanzi: '缺乏',
    pinyin: 'quēfá',
    es: 'carecer de, falta',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['general'],
  },
  {
    id: 'w_chengdan',
    hanzi: '承担',
    pinyin: 'chéngdān',
    es: 'asumir (responsabilidad)',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['trabajo'],
  },
  {
    id: 'w_maodun',
    hanzi: '矛盾',
    pinyin: 'máodùn',
    es: 'contradicción, conflicto',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['sociedad'],
  },
  {
    id: 'w_tuoxie',
    hanzi: '妥协',
    pinyin: 'tuǒxié',
    es: 'ceder, transigir',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
  },
  {
    id: 'w_jinshen',
    hanzi: '谨慎',
    pinyin: 'jǐnshèn',
    es: 'prudente, cauteloso',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['caracter'],
  },
  {
    id: 'w_xianzhu',
    hanzi: '显著',
    pinyin: 'xiǎnzhù',
    es: 'notable, significativo',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
  },
  {
    id: 'w_juxian',
    hanzi: '局限',
    pinyin: 'júxiàn',
    es: 'limitación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
  },
  {
    id: 'w_qingxiang',
    hanzi: '倾向',
    pinyin: 'qīngxiàng',
    es: 'inclinación, tendencia',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
  },
  {
    id: 'w_hengliang',
    hanzi: '衡量',
    pinyin: 'héngliáng',
    es: 'sopesar, evaluar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
  },
  {
    id: 'w_boxue',
    hanzi: '剥削',
    pinyin: 'bōxuē',
    es: 'explotación',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['economia', 'neijuan'],
  },
  {
    id: 'w_kewang',
    hanzi: '渴望',
    pinyin: 'kěwàng',
    es: 'anhelar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['emocion'],
  },
  {
    id: 'w_chenmo',
    hanzi: '沉默',
    pinyin: 'chénmò',
    es: 'silencio, callar',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['emocion'],
  },
  {
    id: 'w_pangda',
    hanzi: '庞大',
    pinyin: 'pángdà',
    es: 'enorme, colosal',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['general'],
  },
  {
    id: 'w_ningju',
    hanzi: '凝聚',
    pinyin: 'níngjù',
    es: 'aglutinar, cohesionar',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
  },
  {
    id: 'w_yanjun',
    hanzi: '严峻',
    pinyin: 'yánjùn',
    es: 'severo, crítico (situación)',
    hsk: 6,
    esChengyu: false,
    dificultad: 6,
    tags: ['sociedad'],
  },
  {
    id: 'w_qianli',
    hanzi: '潜力',
    pinyin: 'qiánlì',
    es: 'potencial',
    hsk: 5,
    esChengyu: false,
    dificultad: 5,
    tags: ['general'],
  },
];
